### ISSUE TITLE
joins

### ISSUE THREAD

**Issue by alanpaulkwan** [phillc73/duckdf#1]
As far as I can tell, there are no joins right? I can use duckdf to query a data.frame / data.table, but when I call inner join it seems like the second table doesn't exist. If it's not hard, it'd be a great feature to add. Thanks so much!

**Comment by phillc73** [comment]
@alanpaulkwan Sincere apologies, but I somehow didn't even see this issue here. Not sure what happened. Anyway, if it's not too late, joins are new supported. Please see the example benchmark in the README using `nycflights13` data. 

At this time, only joining of two tables/dataframes is supported. Joining more than this in a single query will fail.

Please let me know if this works for your use case. If not, I would be pleased to enhance things.
